name: Build the RSE Galaxy image to check the build is successful

on:
  pull_request:
    branches: ['main']

env:
  GALAXY_VERSION: ${{ vars.GALAXY_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./galaxy/
          file: ./galaxy/build/Dockerfile
          push: false
          build-args: |
            GALAXY_VERSION=${{ env.GALAXY_VERSION }}
